[exit] = getExitProp(p_c_bar, eps_conv, eps_div)


out = CEA('problem', 'rocket', 'frozen', 'nfz', 1, ...
                  'case', 'Stark_Conv', 'p,bar', 70, ...
                  'o/f', 4, 'sup', nozzle.epsilon, ...  
                  'reactants', ...
                      'oxid', 'NH4CLO4(I)', 'wt%', 100, 't,k', 298.15, ...
                      'fuel', 'HTPB', 'C', 7.075, 'H', 10.65, 'O', 0.223, 'N', 0.063, ...
                      'h,J/mol', -58000, 'wt%', 100, 't,k', 298.15, ...
                  'output', 'mks', 'transport', 'short', 'end');

 exit.pressure = out.output.froz.pressure(3);
